### ISSUE TITLE
The problem of preprocessing the ScanNet dataset

### ISSUE THREAD

**Issue by ruler9527** [Na-Z/attMPTI#4]
When I run "python collect_scannet_data.py --data_path $path_to_ScanNet_raw_data",  I found that the data obtained after collect_scannet_data did not contain the data with **label 17**. 
So when I run "python ./preprocess/room2blocks.py --data_path ./datasets/ScanNet/scenes/ --dataset scannet" later, **number of scans with class id 17 is 0**. Therefore, during the training of the model, whenever the scene containing class number 17 is sampled, the errors will appear (Because scene contains label 17 is None).
I tried to reprocess the data several times, but it didn't work. I think there are some bugs in the code. I hope you can solve the problems.

**Comment by Na-Z** [comment]
Thanks for pointing out this problem. This bug is due to the name of label 17 which is mistakenly written as `refridgerator` in [scannetv2-labels.combined.tsv](datasets/ScanNet/meta/scannetv2-labels.combined.tsv). 

When I  clean the released code, I update `refridgerator` as `refrigerator` (e.g., in [scannet_classnames.txt](datasets/ScanNet/meta/scannet_classnames.txt)).  This caused the class 17 is not recognized (see [here](https://github.com/Na-Z/attMPTI/blob/d046b36458a5b0c57b4783e597bb180fccc4ddb2/preprocess/collect_scannet_data.py#L24-L28)).

I will correct it in the latest version.
