### ISSUE TITLE
Data preparation about S3DIS step 3

### ISSUE THREAD

**Issue by 964918993** [Na-Z/attMPTI#5]
Hello, I think I need some help with data preprocessing.

I have completed the first two steps of preparation for S3DIS. The generated numpy files are stored in ./datasets/S3DIS/scenes/ by default successfully.

I run 'python ./preprocess/room2blocks.py --data_path=./datasets/S3DIS/scenes/' under the attMPTI folder. It show :
0 scenes to be split...
Total samples: 0

I run 'python room2blocks.py --data_path=../datasets/S3DIS/scenes/' under the preprocess folder. It show:
0 scenes to be split...
Total samples: 0
I don't understand why this problem occurs, when the npy file has already been generated into the default folder.

**Comment by Na-Z** [comment]
Hi. Thanks for pointing out this problem.

It happened because the collected npy files should be put under `./datasets/S3DIS/scenes/data` folder. 

Please check the latest version with the correct save path for both datasets:
https://github.com/Na-Z/attMPTI/blob/7ca79ab928581cfd630d7161fcf728c6fda05bec/preprocess/collect_s3dis_data.py#L70-L71
https://github.com/Na-Z/attMPTI/blob/7ca79ab928581cfd630d7161fcf728c6fda05bec/preprocess/collect_scannet_data.py#L120-L121

**Comment by 964918993** [comment]
Thank you for your reply, but the problem doesn't seem to be solved.

I've put the npy files under ./datasets/S3DIS/scenes/data  and run 
'python room2blocks.py --data_path=/attMPTI-main/datasets/S3DIS/scenes/data/' under the preprocess folder,

 It show:
0 scenes to be split...
Total samples: 0

**Comment by Na-Z** [comment]
Have u tried `python ./preprocess/room2blocks.py --data_path ./datasets/S3DIS/scenes/` under the `attMPTI`?

**Comment by 964918993** [comment]
Thank you very much.
I tried the instruction you said and it works.
